### ISSUE TITLE
Red and blue are swapped

### ISSUE THREAD

**Issue by amadensor** [christopherkobayashi/octoprint-stuff#3]
I made a PR for the webcamd fork, since it is the version I was using, but it would also apply to yours.   It woudl not let me make another fork of yours to make a PR to fix the issue.   It is that OpenCV makes BRG images, but PIL is expecting RBG.  The fix is:
            try:
                **rc, img_bgr = capture.read()**
                if not rc:
                    continue
                **img=cv2.cvtColor(img_bgr,cv2.COLOR_BGR2RGB)**
                jpg = Image.fromarray(img)
                tmpFile = BytesIO()

**Comment by christopherkobayashi** [comment]
Interesting -- wonderful catch, thank you so very much.

Fixed.
